### ISSUE TITLE
getHook is deprecated?

### ISSUE THREAD

**Issue by tkomde** [timfish/forge-externals-plugin#10]
Hi,

I'm using electron-forge 6.1 with webpack and native modules.
I found my native module doesn' t included in the package, so I installed this plugin.
It was loaded but does nothing.

I read [Writing Plugins](https://www.electronforge.io/advanced/extending-electron-forge/writing-plugins) and turned out that getHook may be deprecated and changed to getHooks. Changing getHook to getHooks as follows fixed the probrem.

```
  getHooks() {    
    return {
      resolveForgeConfig: this.resolveForgeConfig,
    };
  }
```

This is very tiny change, so I write to here. If you prefer, I can send a PR.

Best regards,

**Comment by tkomde** [comment]
sorry, same as PR#9

**Comment by timfish** [comment]
0.2.1 has been published!
